### PR TITLE
Added mother info

### LINKED ISSUE #25: Add info button to include mother's name user convention
There's a user convention for certain situations for filling in this field (mother's name):
- If mother's name is still unknown the user writes XX
- If client refuses to provide mother's name, then the user introduces ZZ
- If there's no mother known, then the user introduces JANEDOE

### PR DESCRIPTION
**Pull request by idelcano**
Closes #25

### CODE REVIEW

**Comment by ifoche** [comment]
@idelcano correct me if I'm wrong but I think this PR doesn't have the changes we talked about the other day yet, right?

**Comment by idelcano** [comment]
Sorry @ifoche  Can you refresh me what changes aren't in this PR?
This PR only includes:
- Information button at right of mother label
- Snackbar with the info message

**Comment by ifoche** [comment]
@idelcano at least I can remember you were going to change the "i" color into red so the contrast make it more visible. I can't remember the rest of the changes, but I thought you were taking notes. My fault, I have to always write down the pending tasks in the issues. Please note the PR is "In Progress", so unless you move it to "To test" again, I understand that there's still work in progress. Can you modify the foreground color for the "i" and if you can't remember any further change move it "To test" again? Thanks in advance

**Review by ifoche — APPROVED** [review]
Thanks @idelcano

**Pull request merged**
